name: prueba_itau
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  go_router: ^16.2.5
  get_it: ^8.2.0
  equatable: ^2.0.5
  dio: ^5.7.0
  shared_preferences: ^2.2.3
  connectivity_plus: ^7.0.0
  socket_io_client: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.2
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
